# Add 'feature' label to any PR where the head branch name starts with `feature` or has a `feature` section in the name
feature:
  - head-branch: ["^feat", "feat"]

bug:
  - head-branch: ["^fix", "fix"]

chore:
  - head-branch: ["^chore", "chore"]

perf:
  - head-branch: ["^perf", "perf"]

documentation:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md", "docs/**"]
