ls:
  .js: kebab-case | pointcase
  .vue: kebab-case | pointcase
  .ts: kebab-case | pointcase
  .tsx: kebab-case | pointcase
  .jsx: kebab-case | pointcase
  .css: kebab-case | pointcase
  .d.ts: kebab-case | pointcase
  # shadcn 自动生成文件为 PascalCase 格式
  packages/core/ui-kit/shadcn-ui/src/components/ui:
    .vue: PascalCase

ignore:
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.jpeg"
  - "**/*.jpeg"
  - "**/*.gif"
  - "**/_util.ts"
  - "**/deps/**"
  - "**/dist/**"
  - "**/node_modules/**"
  - "**/.turbo/**"
  - .git
  - .vscode
  - .idea
  - node_modules
  - .cache
