packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/@core/forward/*
  - packages/@core/*
  - packages/effects/*
  - packages/business/*
  - apps/*
  - scripts/*
  - docs
  - playground

overrides:
  '@ast-grep/napi': 'catalog:'
  '@ctrl/tinycolor': 'catalog:'
  clsx: 'catalog:'
  esbuild: 'catalog:'
  jiti: 'catalog:'
  pinia: 'catalog:'
  vue: 'catalog:'
catalog:
  '@ast-grep/napi': ^0.41.0
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@changesets/git': ^3.0.4
  '@clack/prompts': ^1.0.1
  '@commitlint/cli': ^20.4.2
  '@commitlint/config-conventional': ^20.4.2
  '@ctrl/tinycolor': ^4.2.0
  '@eslint-community/eslint-plugin-eslint-comments': ^4.7.1
  '@eslint/js': ^10.0.1
  '@faker-js/faker': ^10.3.0
  '@iconify/json': ^2.2.444
  '@iconify/tailwind': ^1.2.0
  '@iconify/vue': ^5.0.0
  '@intlify/core-base': ^11.2.8
  '@intlify/unplugin-vue-i18n': ^11.0.7
  '@jspm/generator': ^2.11.0
  '@manypkg/get-packages': ^3.1.0
  '@nolebase/vitepress-plugin-git-changelog': ^2.18.2
  '@playwright/test': ^1.58.2
  '@pnpm/workspace.read-manifest': ^1000.2.10
  '@stylistic/stylelint-plugin': ^5.0.1
  '@tailwindcss/nesting': 0.0.0-insiders.565cd3e
  '@tailwindcss/typography': ^0.5.19
  '@tanstack/vue-query': ^5.92.9
  '@tanstack/vue-store': ^0.9.1
  '@types/archiver': ^7.0.0
  '@types/eslint': ^9.6.1
  '@types/html-minifier-terser': ^7.0.2
  '@types/json-bigint': ^1.0.4
  '@types/jsonwebtoken': ^9.0.10
  '@types/lodash.clonedeep': ^4.5.9
  '@types/node': ^25.3.3
  '@types/nprogress': ^0.2.3
  '@types/postcss-import': ^14.0.3
  '@types/qrcode': ^1.5.6
  '@types/qs': ^6.14.0
  '@types/sortablejs': ^1.15.9
  '@typescript-eslint/eslint-plugin': ^8.56.1
  '@typescript-eslint/parser': ^8.56.1
  '@vee-validate/zod': ^4.15.1
  '@vite-pwa/vitepress': ^1.1.0
  '@vitejs/plugin-vue': ^6.0.4
  '@vitejs/plugin-vue-jsx': ^5.1.4
  '@vitest/eslint-plugin': ^1.6.9
  '@vue/shared': ^3.5.29
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^14.2.1
  '@vueuse/integrations': ^14.2.1
  '@vueuse/motion': ^3.0.3
  ant-design-vue: ^4.2.6
  antdv-next: ^1.1.0
  archiver: ^7.0.1
  autoprefixer: ^10.4.27
  axios: ^1.13.6
  axios-mock-adapter: ^2.1.0
  cac: ^7.0.0
  chalk: ^5.6.2
  cheerio: ^1.2.0
  circular-dependency-scanner: ^3.0.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitlint-plugin-function-rules: ^4.3.2
  consola: ^3.4.2
  cross-env: ^10.1.0
  cspell: ^9.7.0
  cssnano: ^7.1.2
  cz-git: ^1.12.0
  czg: ^1.12.0
  dayjs: ^1.11.19
  defu: ^6.1.4
  depcheck: ^1.4.7
  dotenv: ^17.3.1
  echarts: ^6.0.0
  element-plus: ^2.13.3
  es-toolkit: ^1.44.0
  esbuild: ^0.27.3
  eslint: ^10.0.2
  eslint-config-turbo: ^2.8.12
  eslint-plugin-command: ^3.5.2
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^62.7.1
  eslint-plugin-jsonc: ^3.1.1
  eslint-plugin-n: ^17.24.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^5.6.0
  eslint-plugin-pnpm: ^1.6.0
  eslint-plugin-prettier: ^5.5.5
  eslint-plugin-regexp: ^3.0.0
  eslint-plugin-unicorn: ^63.0.0
  eslint-plugin-unused-imports: ^4.4.1
  eslint-plugin-vue: ^10.8.0
  eslint-plugin-yml: ^3.3.0
  execa: ^9.6.1
  find-up: ^8.0.0
  get-port: ^7.1.0
  globals: ^17.4.0
  h3: ^1.15.5
  happy-dom: ^20.7.0
  html-minifier-terser: ^7.2.0
  is-ci: ^4.1.0
  jiti: ^2.6.1
  json-bigint: ^1.0.0
  jsonwebtoken: ^9.0.3
  lefthook: ^2.1.2
  lodash.clonedeep: ^4.5.0
  lucide-vue-next: ^0.576.0
  medium-zoom: ^1.1.0
  naive-ui: ^2.43.2
  nitropack: ^2.13.1
  nprogress: ^0.2.0
  ora: ^9.3.0
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  pkg-types: ^2.3.0
  playwright: ^1.58.2
  postcss: ^8.5.6
  postcss-antd-fixes: ^0.2.0
  postcss-html: ^1.8.1
  postcss-import: ^16.1.1
  postcss-preset-env: ^11.2.0
  postcss-scss: ^4.0.9
  prettier: ^3.8.1
  prettier-plugin-tailwindcss: ^0.7.2
  publint: ^0.3.18
  qrcode: ^1.5.4
  qs: ^6.15.0
  reka-ui: ^2.8.2
  resolve.exports: ^2.0.3
  rimraf: ^6.1.3
  rollup: ^4.59.0
  rollup-plugin-visualizer: ^7.0.0
  sass: ^1.97.3
  secure-ls: ^2.0.0
  sortablejs: ^1.15.7
  stylelint: ^17.4.0
  stylelint-config-recess-order: ^7.6.1
  stylelint-config-recommended: ^18.0.0
  stylelint-config-recommended-scss: ^17.0.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^40.0.0
  stylelint-order: ^7.0.1
  stylelint-prettier: ^5.0.3
  stylelint-scss: ^7.0.0
  tailwind-merge: ^2.6.1
  tailwindcss: ^3.4.19
  tailwindcss-animate: ^1.0.7
  tdesign-vue-next: ^1.18.2
  theme-colors: ^0.1.0
  tippy.js: ^6.3.7
  turbo: ^2.8.12
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unplugin-element-plus: ^0.11.2
  vee-validate: ^4.15.1
  vite: ^7.3.1
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-pwa: ^1.2.0
  vite-plugin-vue-devtools: ^8.0.7
  vitepress: ^1.6.4
  vitepress-plugin-group-icons: ^1.7.1
  vitest: ^4.0.18
  vue: ^3.5.29
  vue-eslint-parser: ^10.4.0
  vue-i18n: ^11.2.8
  vue-json-viewer: ^3.0.4
  vue-router: ^5.0.3
  vue-tippy: ^6.7.1
  vue-tsc: ^3.2.5
  vxe-pc-ui: ^4.13.0
  vxe-table: ^4.17.49
  watermark-js-plus: ^1.6.3
  yaml-eslint-parser: ^2.0.0
  zod: ^3.25.76
  zod-defaults: 0.1.3
