export const listConfig = [
  {
    id: 1,
    name: 'Ad sizes',
    des: 'Estimated earnings by Ad size',
    value: ['AD_UNIT_SIZE_NAME', 'DATE'],
    metrics: [
      'PAGE_VIEWS',
      'IMPRESSIONS',
      'IMPRESSIONS_RPM',
      'IMPRESSIONS',
      'ACTIVE_VIEW_VIEWABILITY',
      'CLICKS',
    ],
    orderBy: ['AD_UNIT_SIZE_NAME', 'DATE'],
  },
  {
    id: 2,
    name: 'Entire account by day',
    des: 'Estimated earnings by Date',
    value: ['DATE'],
    metrics: [
      'PAGE_VIEWS',
      'IMPRESSIONS',
      'IMPRESSIONS_RPM',
      'IMPRESSIONS',
      'ACTIVE_VIEW_VIEWABILITY',
      'CLICKS',
    ],
    orderBy: ['DATE', 'ACCOUNT_NAME'],
  },
  {
    id: 3,
    name: 'Sites',
    des: 'Performance of each site',
    value: ['OWNED_SITE_DOMAIN_NAME'],
    metrics: [
      'PAGE_VIEWS',
      'IMPRESSIONS',
      'IMPRESSIONS_RPM',
      'IMPRESSIONS',
      'ACTIVE_VIEW_VIEWABILITY',
      'CLICKS',
    ],
    orderBy: ['OWNED_SITE_DOMAIN_NAME'],
  },
  {
    id: 4,
    name: 'Ad units',
    des: 'Estimated earnings by Ad unit',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 5,
    name: 'Content platform',
    des: 'Estimated earnings by Platform and Content Platform',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 6,
    name: 'Top pages',
    des: 'Earnings for your popular pages',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 7,
    name: 'Countries',
    des: 'How ads perform by country',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 8,
    name: 'Ad units',
    des: 'Estimated earnings by Ad unit',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 9,
    name: 'Platforms',
    des: 'Estimated earnings by Platform',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 10,
    name: 'Entire account by week',
    des: 'Estimated earnings by Week',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 11,
    name: 'Entire account by month',
    des: 'Estimated earnings by Month',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 12,
    name: 'Custom channels',
    des: 'Estimated earnings by Custom channel',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 13,
    name: 'URL channels',
    des: 'Estimated earnings by URL channels',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 14,
    name: 'Verified sites',
    des: 'Estimated earnings by Verified site',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 15,
    name: 'Served creatives',
    des: 'Estimated earnings by Served creative',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 16,
    name: 'Ad formats',
    des: 'Performance of different ad types',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 17,
    name: 'Creative sizes',
    des: 'Estimated earnings by Creative size',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 18,
    name: 'Targeting types',
    des: 'Estimated earnings by Targeting type',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 19,
    name: 'Bid types',
    des: 'Estimated earnings by Bid type',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 20,
    name: 'Ad networks',
    des: 'Estimated earnings by Ad network',
    value: [],
    metrics: [],
    orderBy: [],
  },
  {
    id: 21,
    name: 'Ad sessions',
    des: 'Estimated earnings by Date',
    value: [],
    metrics: [],
    orderBy: [],
  },
];
