import { useI18n } from '@/hooks/web/useI18n';

const { t } = useI18n();

const METRICS = [
  'ESTIMATED_EARNINGS',
  'COST_PER_CLICK',
  'PAGE_VIEWS_RPM',
  'PAGE_VIEWS',
  'IMPRESSIONS',
  'IMPRESSIONS_RPM',
  'ACTIVE_VIEW_VIEWABILITY',
  'CLICKS',
];

export const TABLE = [
  t('report.ESTIMATED_EARNINGS'),
  t('report.COST_PER_CLICK'),
  t('report.PAGE_VIEWS_RPM'),
  t('report.PAGE_VIEWS'),
  t('report.IMPRESSIONS'),
  t('report.IMPRESSIONS_RPM'),
  t('report.ACTIVE_VIEW_VIEWABILITY'),
  t('report.CLICKS'),
  t('report.METRIC_UNSPECIFIED'),
  t('report.AD_REQUESTS'),
  t('report.MATCHED_AD_REQUESTS'),
  t('report.TOTAL_IMPRESSIONS'),
  t('report.INDIVIDUAL_AD_IMPRESSIONS'),
  t('report.PAGE_VIEWS_SPAM_RATIO'),
  t('report.AD_REQUESTS_SPAM_RATIO'),
  t('report.MATCHED_AD_REQUESTS_SPAM_RATIO'),
  t('report.IMPRESSIONS_SPAM_RATIO'),
  t('report.INDIVIDUAL_AD_IMPRESSIONS_SPAM_RATIO'),
  t('report.CLICKS_SPAM_RATIO'),
  t('report.AD_REQUESTS_COVERAGE'),
  t('report.PAGE_VIEWS_CTR'),
  t('report.AD_REQUESTS_CTR'),
  t('report.MATCHED_AD_REQUESTS_CTR'),
  t('report.IMPRESSIONS_CTR'),
  t('report.INDIVIDUAL_AD_IMPRESSIONS_CTR'),
  t('report.ACTIVE_VIEW_MEASURABILITY'),
  t('report.ACTIVE_VIEW_TIME'),
  t('report.AD_REQUESTS_RPM'),
  t('report.MATCHED_AD_REQUESTS_RPM'),
  t('report.INDIVIDUAL_AD_IMPRESSIONS_RPM'),
  t('report.ADS_PER_IMPRESSION'),
  t('report.TOTAL_EARNINGS'),
  t('report.FUNNEL_REQUESTS'),
  t('report.FUNNEL_IMPRESSIONS'),
  t('report.FUNNEL_CLICKS'),
  t('report.FUNNEL_RPM'),
];
export const listConfig = [
  {
    id: 1,
    name: t('report.Ad sizes'),
    des: t('report.Estimated earnings by Ad size'),
    value: ['AD_UNIT_SIZE_NAME'],
    metrics: [...METRICS],
    orderBy: ['AD_UNIT_SIZE_NAME'],
  },
  {
    id: 2,
    name: t('report.Entire account by day'),
    des: t('report.Estimated earnings by Date'),
    value: ['DATE', 'ACCOUNT_NAME'],
    metrics: [...METRICS],
    orderBy: ['DATE', 'ACCOUNT_NAME'],
  },
  {
    id: 3,
    name: t('report.Sites'),
    des: t('report.Performance of each site'),
    value: ['OWNED_SITE_DOMAIN_NAME'],
    metrics: [...METRICS],
    orderBy: ['OWNED_SITE_DOMAIN_NAME'],
  },
  {
    id: 4,
    name: t('report.Ad units'),
    des: t('report.Estimated earnings by Ad unit'),
    value: ['AD_UNIT_NAME'],
    metrics: [...METRICS],
    orderBy: ['AD_UNIT_NAME'],
  },
  {
    id: 5,
    name: t('report.Content platform'),
    des: t('report.Estimated earnings by Platform and Content Platform'),
    value: ['PLATFORM_TYPE_NAME'],
    metrics: [...METRICS],
    orderBy: ['PLATFORM_TYPE_NAME'],
  },
  {
    id: 6,
    name: t('report.Top pages'),
    des: t('report.Earnings for your popular pages'),
    value: ['PAGE_URL'],
    metrics: [...METRICS],
    orderBy: ['PAGE_URL'],
  },
  {
    id: 7,
    name: t('report.Countries'),
    des: t('report.How ads perform by country'),
    value: ['COUNTRY_NAME'],
    metrics: [...METRICS],
    orderBy: ['COUNTRY_NAME'],
  },
  {
    id: 8,
    name: t('report.Products'),
    des: t('report.Estimated earnings by Product'),
    value: ['PRODUCT_NAME'],
    metrics: [...METRICS],
    orderBy: ['PRODUCT_NAME'],
  },
  {
    id: 9,
    name: t('report.Platforms'),
    des: t('report.Estimated earnings by Platform'),
    value: ['PLATFORM_TYPE_NAME'],
    metrics: [...METRICS],
    orderBy: ['PLATFORM_TYPE_NAME'],
  },
  {
    id: 10,
    name: t('report.Entire account by week'),
    des: t('report.Estimated earnings by Week'),
    value: ['ACCOUNT_NAME', 'WEEK'],
    metrics: [...METRICS],
    orderBy: ['ACCOUNT_NAME', 'WEEK'],
  },
  {
    id: 11,
    name: t('report.Entire account by month'),
    des: t('report.Estimated earnings by Month'),
    value: ['ACCOUNT_NAME', 'MONTH'],
    metrics: [...METRICS],
    orderBy: ['ACCOUNT_NAME', 'MONTH'],
  },
  {
    id: 12,
    name: t('report.Custom channels'),
    des: t('report.Estimated earnings by Custom Channel'),
    value: ['CUSTOM_CHANNEL_NAME'],
    metrics: [...METRICS],
    orderBy: ['CUSTOM_CHANNEL_NAME'],
  },
  {
    id: 13,
    name: t('report.URL channels'),
    des: t('report.Estimated earnings by URL channels'),
    value: ['URL_CHANNEL_NAME'],
    metrics: [...METRICS],
    orderBy: ['URL_CHANNEL_NAME'],
  },
  {
    id: 14,
    name: t('report.Verified sites'),
    des: t('report.Estimated earnings by Verified Site'),
    value: ['OWNED_SITE_DOMAIN_NAME'],
    metrics: [...METRICS],
    orderBy: ['OWNED_SITE_DOMAIN_NAME'],
  },
  {
    id: 15,
    name: t('report.Served creatives'),
    des: t('report.Estimated earnings by Served Creative'),
    value: ['SERVED_AD_TYPE_NAME'],
    metrics: [...METRICS],
    orderBy: ['SERVED_AD_TYPE_NAME'],
  },
  {
    id: 16,
    name: t('report.Ad formats'),
    des: t('report.Performance of different ad types'),
    value: ['AD_FORMAT_NAME'],
    metrics: [...METRICS],
    orderBy: ['AD_FORMAT_NAME'],
  },
  {
    id: 17,
    name: t('report.Creative sizes'),
    des: t('report.Estimated earnings by Creative size'),
    value: ['CREATIVE_SIZE_NAME'],
    metrics: [...METRICS],
    orderBy: ['CREATIVE_SIZE_NAME'],
  },
  {
    id: 18,
    name: t('report.Targeting types'),
    des: t('report.Estimated earnings by Targeting type'),
    value: ['TARGETING_TYPE_NAME'],
    metrics: [...METRICS],
    orderBy: ['TARGETING_TYPE_NAME'],
  },
  {
    id: 19,
    name: t('report.Bid types'),
    des: t('report.Estimated earnings by Bid type'),
    value: ['BID_TYPE_NAME'],
    metrics: [...METRICS],
    orderBy: ['BID_TYPE_NAME'],
  },
  {
    id: 20,
    name: t('report.Ad networks'),
    des: t('report.Estimated earnings by Ad network'),
    value: ['BUYER_NETWORK_NAME'],
    metrics: [...METRICS],
    orderBy: ['BUYER_NETWORK_NAME'],
  },
];
