version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vben_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vben_admin
    ports:
      - '3306:3306'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:alpine
    container_name: vben_redis
    restart: always
    ports:
      - '16379:6379'
