export const SYSTEM_PLATFORM_MENUS = [
  {
    path: '/finance',
    name: 'FinanceManagement',
    component: 'LAYOUT',
    meta: {
      icon: 'lucide:wallet',
      order: 90,
      title: '财务管理',
    },
    children: [
      {
        path: '/finance/reimbursement',
        name: 'FinanceReimbursement',
        component: '/finance/reimbursement/index',
        meta: { icon: 'lucide:receipt-text', title: '报销单查询' },
      },
      {
        path: '/finance/payment',
        name: 'FinancePayment',
        component: '/finance/payment/index',
        meta: { icon: 'lucide:banknote-arrow-up', title: '支付单查询' },
      },
      {
        path: '/finance/voucher',
        name: 'FinanceVoucher',
        component: '/finance/voucher/index',
        meta: { icon: 'lucide:file-text', title: '凭证查询' },
      },
    ],
  },
  {
    path: '/sys',
    name: 'SysManagement',
    component: 'LAYOUT',
    meta: {
      icon: 'lucide:settings',
      order: 100,
      title: '系统管理',
    },
    children: [
      {
        path: '/sys/config',
        name: 'SysConfig',
        component: '/sys/config/index',
        meta: { icon: 'lucide:sliders-horizontal', title: '组织参数设置' },
      },
      {
        path: '/sys/dict',
        name: 'SysDict',
        component: '/sys/dict/index',
        meta: { icon: 'lucide:book-marked', title: '基础数据' },
      },
      {
        path: '/sys/tenant-parameter',
        name: 'SysTenantParameter',
        component: '/sys/tenant-parameter/index',
        meta: { icon: 'lucide:sliders-vertical', title: '账套参数设置' },
      },
      {
        path: '/sys/tenant-policy',
        name: 'SysTenantPolicy',
        component: '/sys/tenant-policy/index',
        meta: { icon: 'lucide:sliders', title: '租户策略设置' },
      },
      {
        path: '/sys/user',
        name: 'SysUser',
        component: '/sys/user/index',
        meta: { icon: 'lucide:users', title: '用户管理' },
      },
      {
        path: '/sys/role',
        name: 'SysRole',
        component: '/sys/role/index',
        meta: { icon: 'lucide:user-check', title: '角色管理' },
      },
      {
        path: '/sys/dept',
        name: 'SysDept',
        component: '/sys/dept/index',
        meta: { icon: 'lucide:network', title: '组织机构主数据' },
      },
      {
        path: '/sys/post',
        name: 'SysPost',
        component: '/sys/post/index',
        meta: { icon: 'lucide:briefcase', title: '岗位基础档案' },
      },
      {
        path: '/sys/menu',
        name: 'SysMenu',
        component: '/sys/menu/index',
        meta: { icon: 'lucide:menu', title: '菜单管理' },
      },
      {
        path: '/sys/approval/my-todo',
        name: 'SysApprovalMyTodo',
        component: '/sys/approval-process/my-approval',
        meta: { icon: 'lucide:clipboard-check', title: '我的审批' },
      },
      {
        path: '/sys/approval/pending',
        name: 'SysApprovalPending',
        component: '/sys/approval-process/pending',
        meta: { icon: 'lucide:clock-3', title: '待审流程' },
      },
      {
        path: '/sys/approval/my-submit',
        name: 'SysApprovalMySubmit',
        component: '/sys/approval-process/my-submit',
        meta: { icon: 'lucide:send', title: '我的提交' },
      },
      {
        path: '/sys/approval/approved',
        name: 'SysApprovalApproved',
        component: '/sys/approval-process/approved',
        meta: { icon: 'lucide:badge-check', title: '审批通过' },
      },
      {
        path: '/sys/approval/cc-to-me',
        name: 'SysApprovalCcToMe',
        component: '/sys/approval-process/cc-to-me',
        meta: { icon: 'lucide:mail-open', title: '抄送我的' },
      },
      {
        path: '/sys/approval/all',
        name: 'SysApprovalAll',
        component: '/sys/approval-process/all-approval',
        meta: { icon: 'lucide:files', title: '全部审批' },
      },
      {
        path: '/sys/approval/flow-config',
        name: 'SysApprovalFlowConfig',
        component: '/sys/approval-process/flow-config',
        meta: { icon: 'lucide:git-branch-plus', title: '审批流程配置' },
      },
      {
        path: '/sys/form/todo',
        name: 'SysFlowTodo',
        component: '/sys/form-design/todo',
        meta: { icon: 'lucide:list-todo', title: '待办流程' },
      },
      {
        path: '/sys/form/done',
        name: 'SysFlowDone',
        component: '/sys/form-design/done',
        meta: { icon: 'lucide:check-check', title: '已办流程' },
      },
      {
        path: '/sys/form/cc',
        name: 'SysFlowCc',
        component: '/sys/form-design/cc',
        meta: { icon: 'lucide:mail-plus', title: '抄送流程' },
      },
      {
        path: '/sys/form/initiate',
        name: 'SysFlowInitiate',
        component: '/sys/form-design/initiate',
        meta: { icon: 'lucide:play-circle', title: '发起流程' },
      },
      {
        path: '/sys/form/my-submit',
        name: 'SysFlowMySubmit',
        component: '/sys/form-design/my-submit',
        meta: { icon: 'lucide:file-clock', title: '流程我的提交' },
      },
      {
        path: '/sys/form/config',
        name: 'SysFormConfig',
        component: '/sys/form-design/form-config',
        meta: { icon: 'lucide:layout-template', title: '表单配置' },
      },
      {
        path: '/sys/expense-claim',
        name: 'SysExpenseClaim',
        component: '/sys/expense-claim/index',
        meta: { icon: 'lucide:receipt', title: '报销单' },
      },
      {
        path: '/sys/research-project',
        name: 'SysResearchProject',
        component: '/sys/research-project/index',
        meta: { icon: 'lucide:flask-conical', title: '科研项目' },
      },
      {
        path: '/sys/research-fund-arrival',
        name: 'SysResearchFundArrival',
        component: '/sys/research-fund-arrival/index',
        meta: { icon: 'lucide:banknote-arrow-down', title: '资金到账' },
      },
      {
        path: '/sys/research-fund-claim',
        name: 'SysResearchFundClaim',
        component: '/sys/research-fund-claim/index',
        meta: { icon: 'lucide:hand-coins', title: '资金认领' },
      },
      {
        path: '/sys/research-indicator',
        name: 'SysResearchIndicator',
        component: '/sys/research-indicator/index',
        meta: { icon: 'lucide:badge-dollar-sign', title: '科研指标' },
      },
      {
        path: '/sys/research-expense-scope',
        name: 'SysResearchExpenseScope',
        component: '/sys/research-expense-scope/index',
        meta: { icon: 'lucide:wallet-cards', title: '支出范围' },
      },
      {
        path: '/sys/research-scope-adjust',
        name: 'SysResearchScopeAdjust',
        component: '/sys/research-scope-adjust/index',
        meta: { icon: 'lucide:arrow-left-right', title: '范围调剂' },
      },
      {
        path: '/sys/tenant',
        name: 'SysTenant',
        component: '/sys/tenant/index',
        meta: { icon: 'lucide:building-2', title: '账套维护' },
      },
      {
        path: '/sys/contract',
        name: 'SysContract',
        component: '/sys/contract/index',
        meta: { icon: 'lucide:file-signature', title: '合同台账' },
      },
      {
        path: '/sys/contract-receipt',
        name: 'SysContractReceipt',
        component: '/sys/contract-receipt/index',
        meta: { icon: 'lucide:badge-check', title: '合同到账' },
      },
      {
        path: '/sys/procurement-apply',
        name: 'SysProcurementApply',
        component: '/sys/procurement-apply/index',
        meta: { icon: 'lucide:shopping-cart', title: '采购申报' },
      },
      {
        path: '/sys/procurement-result',
        name: 'SysProcurementResult',
        component: '/sys/procurement-result/index',
        meta: { icon: 'lucide:clipboard-check', title: '采购结果' },
      },
      {
        path: '/sys/bid-notice',
        name: 'SysBidNotice',
        component: '/sys/bid-notice/index',
        meta: { icon: 'lucide:megaphone', title: '招标公告' },
      },
    ],
  },
];

export default SYSTEM_PLATFORM_MENUS;
